// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWLZe-ByWA_vAfaykHVXmDCJ1IgS27ZUk',
    appId: '1:24287018059:web:51ebe17610bfb1f7e361ce',
    messagingSenderId: '24287018059',
    projectId: 'bitewise-edcd6',
    authDomain: 'bitewise-edcd6.firebaseapp.com',
    storageBucket: 'bitewise-edcd6.firebasestorage.app',
    measurementId: 'G-1QNQBXC88M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBisYcXBi6hkiK2LwHceQfP-psqLhSeRmc',
    appId: '1:24287018059:android:527bd7f7ec829b54e361ce',
    messagingSenderId: '24287018059',
    projectId: 'bitewise-edcd6',
    storageBucket: 'bitewise-edcd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrycLnuCaQsyR8CK__kixfEUKzKjAxKQc',
    appId: '1:24287018059:ios:be434fecf52e9e8ce361ce',
    messagingSenderId: '24287018059',
    projectId: 'bitewise-edcd6',
    storageBucket: 'bitewise-edcd6.firebasestorage.app',
    iosBundleId: 'com.example.bitewise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrycLnuCaQsyR8CK__kixfEUKzKjAxKQc',
    appId: '1:24287018059:ios:be434fecf52e9e8ce361ce',
    messagingSenderId: '24287018059',
    projectId: 'bitewise-edcd6',
    storageBucket: 'bitewise-edcd6.firebasestorage.app',
    iosBundleId: 'com.example.bitewise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWLZe-ByWA_vAfaykHVXmDCJ1IgS27ZUk',
    appId: '1:24287018059:web:fda20eef1ea6aa8de361ce',
    messagingSenderId: '24287018059',
    projectId: 'bitewise-edcd6',
    authDomain: 'bitewise-edcd6.firebaseapp.com',
    storageBucket: 'bitewise-edcd6.firebasestorage.app',
    measurementId: 'G-QGPBK3493X',
  );
}
