import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../viewmodel/language_view_model.dart';

class AppText {
  static final Map<String, Map<String, String>> _texts = {
    'en': {
      'appName': 'BiteWise',
      'login': 'Login',
      'register': 'Register',
      'createAccount': 'Create Account',
      'email': 'Email',
      'password': 'Password',
      'forgotPassword': 'Forgot Password?',
      'logout': 'Logout',
      'settings': 'Settings',
      'language': 'Language',
      'english': 'English',
      'arabic': 'Arabic',
      'switchLanguage': 'Switch app language',
      'mealHistory': 'Meal History',
      'noMealsYet': 'No meals yet',
      'analyzeImage': 'Analyze Image',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'breakfast': 'Breakfast',
      'lunch': 'Lunch',
      'dinner': 'Dinner',
      'snack': 'Snack',
      'calories': 'Calories',
      'protein': 'Protein',
      'carbs': 'Carbs',
      'fat': 'Fat',
      'save': 'Save',
      'cancel': 'Cancel',
      'ok': 'OK',
      'selectMealType': 'Select Meal Type',
      'foodScanner': 'Food Scanner',
'takePhoto': 'Take Photo',
'uploadFromGallery': 'Upload From Gallery',
'aiAssistant': 'AI Assistant',
'typeMessage': 'Type a message...',
'aiTyping': 'AI is typing...',

'deleteAccount': 'Delete Account',
'deleteAccountWarning': 'This will permanently delete your account and all your data.',
'enterPassword': 'Enter your password',
'deleteAccountPermanently': 'Delete Account Permanently',
'passwordRequired': 'Password is required',
'somethingWentWrong': 'Something went wrong',
'incorrectPassword': 'Incorrect password',
'pleaseTryAgain': 'Please try again',
'error': 'Error',
'food': 'Food',
'meal': 'Meal',

'kcal': 'kcal',

'dailyPlan': 'Daily Plan',
'generatePlan': 'Generate Plan',
'generateNewPlan': 'Generate New Plan',
'total': 'Total',
'setupProfile': 'Setup Your Profile 🚀',
'profileSetupSubtitle': 'We need some info to personalize your AI coach',
'name': 'Name',
'age': 'Age',
'heightCm': 'Height (cm)',
'weightKg': 'Weight (kg)',
'diseaseOptional': 'Disease (optional)',
'gender': 'Gender',
'female': 'Female',
'male': 'Male',
'activityLevel': 'Activity Level',
'sedentary': 'Sedentary',
'light': 'Light',
'moderate': 'Moderate',
'veryActive': 'Very Active',
'yourGoal': 'Your Goal',
'lose': 'Lose',
'maintain': 'Maintain',
'gain': 'Gain',
'fillRequiredFields': 'Please fill all required fields',

'continueText': 'Continue',

'registerSubtitle': 'Start your smart nutrition journey',
'emailAddress': 'Email address',

'confirmPassword': 'Confirm Password',

'alreadyHaveAccount': 'Already have an account?',
'emailRequired': 'Email is required',
'validEmailRequired': 'Enter a valid email address',

'passwordMinLength': 'Password must be at least 8 characters',
'uppercaseRequired': 'Must contain an uppercase letter',
'lowercaseRequired': 'Must contain a lowercase letter',
'numberRequired': 'Must contain a number',
'confirmPasswordRequired': 'Please confirm your password',
'passwordsDoNotMatch': 'Passwords do not match',
'registerFailed': 'Register failed',
'result': 'Result',
'noData': 'No Data',
'enterMealDetails': 'Enter your meal details',
'enterMealDetailsFirst': 'Enter meal details first',
'calculateMacros': 'Calculate Macros',
'nutritionSummary': 'Nutrition Summary',
'advice': 'Advice',
'alternativeMeal': 'Alternative Meal',
'mealSavedSuccessfully': 'Meal saved successfully',
'saving': 'Saving...',
'saveMeal': 'Save Meal',
'enterQuantityFirst': 'Enter quantity first to get advice.',

'fats': 'Fats',
'fiber': 'Fiber',



'goal': 'Goal',

'darkMode': 'Dark Mode',
'saveChanges': 'Save Changes',

'updated': 'Updated',

'loginSubtitle': 'Smart nutrition. Clean choices.',

'newHere': 'New here?',

'resetPassword': 'Reset Password',
'enterYourEmail': 'Enter your email',

'send': 'Send',
'passwordResetSent': 'Password reset email sent successfully.',

'validGmailRequired': 'Enter a valid Gmail address',

'invalidEmailAddress': 'Invalid email address',
'noAccountFound': 'No account found with this email',
'invalidEmailOrPassword': 'Invalid email or password',

'loginFailed': 'Login failed',

'weeklyCalories': 'Weekly Calories',

'monday': 'M',
'tuesday': 'T',
'wednesday': 'W',
'thursday': 'T',
'friday': 'F',
'saturday': 'S',
'sunday': 'S',
      'today': 'Today',
'caloriesConsumed': 'Calories Consumed',

'dailyCalories': 'Daily Calories',
'dailyTarget': 'Daily target',
'remaining': 'Remaining',
'caloriesLeft': 'Calories Left',
'ofGoal': 'of goal',
'left': 'left',
'thisWeek': 'This Week',
'selectedWeek': 'Selected Week',
'welcome':'welcom',

'weeklyGoal': 'Weekly Goal',

'highestIntake': 'Highest Intake',
'streak': 'Streak',

'days': 'days',
'nutritionFacts':'Netrition Facts',
'mealDetails':'Meal Details',

    },
    'ar': {
      'appName': 'بايت وايز',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'createAccount': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'logout': 'تسجيل الخروج',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'switchLanguage': 'تغيير لغة التطبيق',
      'mealHistory': 'سجل الوجبات',
      'noMealsYet': 'لا توجد وجبات بعد',
      'analyzeImage': 'تحليل الصورة',
      'camera': 'الكاميرا',
      'gallery': 'المعرض',
      'breakfast': 'فطور',
      'lunch': 'غداء',
      'dinner': 'عشاء',
      'snack': 'سناك',
      'calories': 'السعرات الحرارية',
      'protein': 'البروتين',
      'carbs': 'الكربوهيدرات',
      'fat': 'الدهون',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'ok': 'موافق',
      'selectMealType': 'اختاري نوع الوجبة',
      'foodScanner': 'ماسح الطعام',
'takePhoto': 'التقاط صورة',
'uploadFromGallery': 'رفع من المعرض',
'aiAssistant': 'المساعد الذكي',
'typeMessage': 'اكتبي رسالة...',
'aiTyping': 'المساعد يكتب...',
'deleteAccount': 'حذف الحساب',
'deleteAccountWarning': 'سيتم حذف حسابك وجميع بياناتك بشكل دائم.',
'enterPassword': 'أدخلي كلمة المرور',
'deleteAccountPermanently': 'حذف الحساب نهائياً',
'passwordRequired': 'كلمة المرور مطلوبة',
'somethingWentWrong': 'حدث خطأ ما',
'incorrectPassword': 'كلمة المرور غير صحيحة',
'pleaseTryAgain': 'يرجى المحاولة مرة أخرى',
'error': 'خطأ',
'food': 'طعام',
'meal': 'وجبة',
'kcal': 'سعرة',
'dailyPlan': 'الخطة اليومية',
'generatePlan': 'إنشاء خطة',
'generateNewPlan': 'إنشاء خطة جديدة',
'total': 'المجموع',
  'setupProfile': 'إعداد الملف الشخصي 🚀',
'profileSetupSubtitle': 'نحتاج بعض المعلومات لتخصيص مدربك الذكي',
'name': 'الاسم',
'age': 'العمر',
'heightCm': 'الطول (سم)',
'weightKg': 'الوزن (كغم)',
'diseaseOptional': 'مرض أو حالة صحية (اختياري)',
'gender': 'الجنس',
'female': 'أنثى',
'male': 'ذكر',
'activityLevel': 'مستوى النشاط',
'sedentary': 'قليل الحركة',
'light': 'خفيف',
'moderate': 'متوسط',
'veryActive': 'نشط جداً',
'yourGoal': 'هدفك',
'lose': 'خسارة',
'maintain': 'ثبات',
'gain': 'زيادة',
'fillRequiredFields': 'يرجى تعبئة جميع الحقول المطلوبة',
'continueText': 'متابعة',
  
'registerSubtitle': 'ابدئي رحلتك الذكية في التغذية',
'emailAddress': 'البريد الإلكتروني',

'confirmPassword': 'تأكيد كلمة المرور',

'alreadyHaveAccount': 'لديك حساب بالفعل؟',
'emailRequired': 'البريد الإلكتروني مطلوب',
'validEmailRequired': 'أدخلي بريد إلكتروني صحيح',

'passwordMinLength': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
'uppercaseRequired': 'يجب أن تحتوي على حرف كبير',
'lowercaseRequired': 'يجب أن تحتوي على حرف صغير',
'numberRequired': 'يجب أن تحتوي على رقم',
'confirmPasswordRequired': 'يرجى تأكيد كلمة المرور',
'passwordsDoNotMatch': 'كلمتا المرور غير متطابقتين',
'registerFailed': 'فشل إنشاء الحساب',

'result': 'النتيجة',
'noData': 'لا توجد بيانات',
'enterMealDetails': 'أدخلي تفاصيل الوجبة',
'enterMealDetailsFirst': 'أدخلي تفاصيل الوجبة أولاً',
'calculateMacros': 'حساب القيم الغذائية',
'nutritionSummary': 'ملخص القيم الغذائية',
'advice': 'نصيحة',
'alternativeMeal': 'وجبة بديلة',
'mealSavedSuccessfully': 'تم حفظ الوجبة بنجاح',
'saving': 'جاري الحفظ...',
'saveMeal': 'حفظ الوجبة',
'enterQuantityFirst': 'أدخلي الكمية أولاً للحصول على نصيحة.',

'fats': 'الدهون',
'fiber': 'الألياف',

'goal': 'الهدف',

'darkMode': 'الوضع الداكن',
'saveChanges': 'حفظ التغييرات',

'updated': 'تم التحديث',
'loginSubtitle': 'تغذية ذكية. اختيارات صحية.',

'newHere': 'جديدة هنا؟',

'resetPassword': 'إعادة تعيين كلمة المرور',
'enterYourEmail': 'أدخلي بريدك الإلكتروني',

'send': 'إرسال',
'passwordResetSent': 'تم إرسال رابط إعادة تعيين كلمة المرور بنجاح.',

'validGmailRequired': 'أدخلي بريد Gmail صحيح',

'invalidEmailAddress': 'البريد الإلكتروني غير صحيح',
'noAccountFound': 'لا يوجد حساب بهذا البريد الإلكتروني',
'invalidEmailOrPassword': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',

'loginFailed': 'فشل تسجيل الدخول',
'weeklyCalories': 'السعرات الأسبوعية',

'monday': 'ا',
'tuesday': 'ث',
'wednesday': 'أ',
'thursday': 'خ',
'friday': 'ج',
'saturday': 'س',
'sunday':'أ',
'today': 'اليوم',
'caloriesConsumed': 'السعرات المستهلكة',

'dailyCalories': 'السعرات اليومية',
'dailyTarget': 'الهدف اليومي',
'remaining': 'المتبقي',
'caloriesLeft': 'السعرات المتبقية',
'ofGoal': 'من الهدف',
'left': 'متبقي',
'thisWeek': 'هذا الأسبوع',
'selectedWeek': 'الأسبوع المحدد',
'weeklyGoal': 'الهدف الأسبوعي',

'highestIntake': 'أعلى استهلاك',
'streak': 'الأيام المتتالية',
'welcome':'اهلا و سهلا',
'days': 'أيام',
'mealDetails':'تفاصيل الوجبة',
'nutritionFacts':'حقائق غذائية',
    },
  };

  static String get(BuildContext context, String key) {
    final languageCode = context.watch<LanguageViewModel>().locale.languageCode;

    return _texts[languageCode]?[key] ?? _texts['en']?[key] ?? key;
  }
}